#!/bin/bash

################################################################################
##  NIV(Network Interface Viewer) is alternative of ifconfig.                 ##
##  It has simple view and show only active network interfaces.               ##
##  https://github.com/ekcode/niv                                             ##
################################################################################

for ETH in $(ifconfig -l); do
    status=$(ifconfig "$ETH" | grep status | awk '{print $2}')
    if [ "$status" = "active" ]; then
        printf "\n%10s \033[0;31m => \033[m %-20s\n" "interface" "$ETH"
        ifconfig -v "$ETH" | grep -E "inet|type|ether" | sed 's/: / /' | awk '{printf "%10s \033[0;92m => \033[m %-20s\n", $1, $2}'
    fi
done

